pipeline{    
    agent{
        docker{
            image "ubuntu:latest"
        }
    }

    stages{        
        stage("pull"){
            steps{
                sh """
                    ls
                    """
            }
        }

    }
}