pipeline{    
    stages{
        stage("pull"){
            steps{
                sh"""
                    docker pull carlos6125/demo
                """
            }   
        }

        stage("run"){
            steps{
                sh """
                    docker run --rm carlos6125/demo
                    """
            }
        }
    }
}