pipeline{
    agent{
        docker{
            image 'carlos6125/demo'
            args '-p 3000:3000'
        }
    }

    // stages {
    //     stage('Build'){
    //         steps{
    //             sh 'npm install'
    //         }
    //     }
    // }

}